### ISSUE TITLE
Clean buildFeatures

### ISSUE THREAD

**Issue by jbpratt78** [MemeLabs/chat-gui#10]
https://github.com/MemeLabs/chat-gui/blob/e2abcbf7899b39b93252edaf03e7b697e3d18bd2/assets/chat/js/messages.js#L33

None of the subscriber or birthday features are used. Maybe VIP, Notable, and Contributor can go as well in my opinion. BERN

**Comment by jbpratt78** [comment]
https://github.com/MemeLabs/chat-gui/blob/e2abcbf7899b39b93252edaf03e7b697e3d18bd2/assets/chat/js/features.js as well

**Comment by xDashh** [comment]
Does them being there make anything more complicated or slower?
Some (e.g. SC2) will probably never be used, but keeping them doesn't. Contributor/Notable/VIP or similar might be used again in the future.

**Comment by jbpratt78** [comment]
Just the extra I spotted when looking for the blank span in front of mods names. Can close if no interest

**Comment by slugalisk** [comment]
@xDashh the reason this came up was that admins have an empty span in front of their names with padding that breaks the alignment with the rest of the names. Since this sort of looks buggy it might be a good idea to comment the flairs feature out until we decide what we want to do with it.

**Comment by xDashh** [comment]
I see. If removing the mod flair doesn't break anything else I wouldn't mind.
I'd skip removing ones that don't have negative impact though.
@slugalisk @jbpratt78

**Comment by xDashh** [comment]
Partly addressed by https://github.com/MemeLabs/chat-gui/issues/38
