### ISSUE TITLE
Proposal: Our own rendition of the "Golden Kappa". Open for discussion.

### ISSUE THREAD

**Issue by jbpratt78** [MemeLabs/chat-gui#106]

**Comment by SoMuchForSubtlety** [comment]
maybe relevant https://github.com/MemeLabs/chat-gui/issues/39

**Comment by xDashh** [comment]
Yep, closing in favor of https://github.com/MemeLabs/chat-gui/issues/39. That was the intention when opening the other one: building a more generalized system for defining time-slots, rarity, and eligibility for special emotes.
