### ISSUE TITLE
onstreamchat fixes

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#113]
Code tags (and I assume spoiler-tags, but untested) aren't displayed well on the on-stream-chat.

**Comment by WhiteNervosa** [comment]
You could make the box have a SPOILER tag that when clicked grows into the larger message

```
.spoiler:before {
    content: "[SPOILER]";
    z-index: 1;
    font-size: small;
    color: #828282;
    font-weight: 500;
    padding-right: 0.5em;
    position: absolute;
}

.msg-chat .spoiler {
    padding-right: 3px;
    border-radius: 3px;
    border-width: 1px;
    border-style: solid;
    border-color: #000000;
    transition: all .4s ease-in-out;
    background: #222222;
    color: transparent;
    width: 70px;
    height: 22px;
    padding-left: 5px;
    overflow: hidden;
    display: inline;
    position: absolute;
}
```

https://streamable.com/k3t5v

**Comment by jbpratt78** [comment]
I think the original issue was referencing https://chat.strims.gg/chatstreamed rather than the normal chat, though this could be a fix for a different issue.

**Comment by WhiteNervosa** [comment]
Oh yeah, I just don't really have a way to test that myself. But if the code is applied to the onstream CSS then it would make it just the small [SPOILER] label rather than a black box taking up two lines, as I quite like the way its currently implemented in chat.
