### ISSUE TITLE
fix notification permission request

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#12]
Since chat is hosted on a different subdomain, when using the site normally, it seems like chat cannot or does not (for some reason) ask for the notification (on chat highlight) permission correctly.

**Comment by JoannesJ** [comment]
It seems this issue only applies to Blink browsers, as they have removed permission requests from iframes.
According to [this](https://www.chromestatus.com/feature/6451284559265792), Edge has shown support for this removal. But currently it still works in Edge, and I can't find a statement. So I think it's save to leave it as is in Edge.

So the solution is spawning a popup from the "chat.strims" domain and requesting permission from there. On mobile this spawns a new tab.

The only shitty thing is that the Blink implementation doesn't distinguish between a permission denied by the user or a permission denied by the browser. So would need to do browser detection, which is shit.

**Comment by xDashh** [comment]
Fixed by https://github.com/MemeLabs/chat-gui/pull/23
