### ISSUE TITLE
Update styling

### ISSUE THREAD

**Issue by JoannesJ** [MemeLabs/chat-gui#38]
Update Styling:
- Make chat distinguishable from dgg
- Remove lingering dgg icons
- Remove the spacing in front of chat Offiziere (RTBA asked about it)
- Make style match Rustla

@xDashh assign me!

**Comment by JoannesJ** [comment]
I had also looked at making the slash-me thing more distinguishable and true to the meme.

![msg-me-example](https://user-images.githubusercontent.com/13875387/47945683-e3876f80-df03-11e8-9d83-0322ebdce285.png)

**Comment by JoannesJ** [comment]
@xDashh Here are two possible differentiation for same channel messages.
Darker user name block for different channel:
![firefox_2018-11-03_16-25-16](https://user-images.githubusercontent.com/13875387/47954355-e036c700-df89-11e8-9d40-d370f393cffc.png)
Chevron character for same channel:
![firefox_2018-11-03_16-46-08](https://user-images.githubusercontent.com/13875387/47954356-e2008a80-df89-11e8-99d8-67a7ef6582a0.png)

**Comment by xDashh** [comment]
I think both (/me and the names) look nice (/me might lead to bit more abuse/spam but let's see). For now I'd say we can just add the box to every username and if we need it we can later re-purpose it for the per-channel highlight still.

@KenanY or @Oreganon does anyone have comments on it?

**Comment by Oreganon** [comment]
Looks good PepOk

**Comment by xDashh** [comment]
Closed by https://github.com/MemeLabs/chat-gui/pull/40
