### ISSUE TITLE
Generate proper favicons

### ISSUE THREAD

**Issue by JoannesJ** [MemeLabs/chat-gui#43]
Would be nice to have the proper favicons for things like the "new tab page" in Firefox.

This how it currently looks:
![firefox_2018-11-09_19-40-02](https://user-images.githubusercontent.com/13875387/48281735-ca2c7900-e457-11e8-806b-f79d29a3af3e.png)

**Comment by xDashh** [comment]
Supposedly this site can do the magic http://tools.dynamicdrive.com/favicon/.
I just dont have the source image for the icon handy atm.

Reminder to also add the icon to https://github.com/MemeLabs/Rustla2/tree/master/public/image

**Comment by xDashh** [comment]
Hopefully resolved by https://github.com/MemeLabs/chat-gui/commit/aef9a013ed1eda783bc9149c8a76d8b2ea8e9eb4 without breaking anything. 
It should look like https://i.imgur.com/9uvMCEz.png now (the chat domain anyway. Main domain commit pending)
