### ISSUE TITLE
Display timestamp for automatically generated embed links in chat

### ISSUE THREAD

**Issue by Ajukirurg** [MemeLabs/chat-gui#446]
Reason (Why?)
The new feature that turns links from chat into embeds should not hide the timestamp. Clicking on the link changes the stream you are watching which makes sense if its a livestream, a long clip, or I am just chilling on the mainpage anyway. It doesn't make much sense for the user when it is just a quick timestamp which would prompt me to go back to the mainpage immediately after.

Generally turning timestamped videos into a strims embed is still a desired behaviour though so you can somewhat watch a longer youtube vid in sync with multiple chatters.

Solution (What?)
Either display the full URL or add some indicator to the link that it is a timestamped video.

**Comment by slugalisk** [comment]
@Ajukirurg can you provide an example? i thought using the original url would be misleading since it opens in a frame now but we can include the full path/query if that's what you want.

**Comment by jbpratt** [comment]
closed with 0879fdc

skipping enrichment on timestamped videos
