### ISSUE TITLE
Input box doesn't clear after sending message

### ISSUE THREAD

**Issue by talleyp** [MemeLabs/chat-gui#459]
[Example]( https://i.imgur.com/t0QUDjG.mp4)
 
After hitting enter the message stays in the input box. When enter is hit a second time the message clears with the identical message warning.

Cookies and cache was cleared and after browser restart the issue persists.

Firefox 89.0.2 (64 bit)
Ubuntu 20.04.2

**Comment by x-Xymos** [comment]
This is caused by exceeding the maximum memory limit of a local storage item

https://i.imgur.com/YY49PFJ.png

https://stackoverflow.com/a/65676273
