### ISSUE TITLE
user-name tab complete resets erroneously

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#48]
Finally able to reproduce, but probably unrelated to other open tab-complete issues, so opening a new one for this instance:

2 users in chat: `jbizzlez` and `jbpratt`.

Type `jb<tab>`, should complete to `jbizzlez` (alphabetical sorting, assuming no prior state). Continue tabbing to `jbpratt` and finish typing `jbpratt test123`. Now our last tab-complete state for "jb" (or however chat remembers that) is `jbpratt`. Type `jb<tab>` again and it should tab `jbpratt` first.

Now `jbpratt` types a message in chat. Following that typing `jb<tab>` will opt to tab-complete to `jbizzlez` again, ignoring our prior tab-complete. (this is the bug)

**Comment by JoannesJ** [comment]
When a message is received the user of that message is added to the autocomplete again.
The problem is that the default parameter value overrides the previously gained "weight".
https://github.com/MemeLabs/chat-gui/blob/d3f06625b966ac31de18bffe10acb1754504d774/assets/chat/js/autocomplete.js#L241

**Comment by xDashh** [comment]
(Hopefully) fixed by https://github.com/MemeLabs/chat-gui/pull/49.
