### ISSUE TITLE
stop animating old emotes

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#83]
Having infinite loop animation active reportedly causes CPU issues for some people.

Since browsers are not smart enough yet to stop animating emotes that are "out of sight", stop animating them programmatically for messages that are "too old".
Ideally this would be switched dynamically once they scroll out of view, but a good heuristic would be to disable animations for all messages that are ~35-40 messages into the backlog.

**Comment by slugalisk** [comment]
via laetus https://stackoverflow.com/questions/4844456/is-it-possible-to-select-the-last-n-items-with-nth-child

**Comment by xDashh** [comment]
```div .chat-lines .msg-chat:nth-last-child(n+30) .generify-container .chat-emote {animation: none}```

seems to work in dev tools. Now I have to figure out where/how to put that in code.

**Comment by xDashh** [comment]
Let's hope that does it https://github.com/MemeLabs/chat-gui/commit/035f1f749dd5e49aaea78f66e8817907fce2ae28.
