### ISSUE TITLE
fix code formatting patch

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/chat-gui#97]
Lines starting with an emote do not correctly format that emote.
Introduced with https://github.com/MemeLabs/chat-gui/commit/462acae22633bd77ac9480869122048e29e3d1f1

**Comment by SoMuchForSubtlety** [comment]
Probably introduced here https://github.com/MemeLabs/chat-gui/commit/462acae22633bd77ac9480869122048e29e3d1f1#diff-4f24595caa90170de9accc7ca874f505R137

**Comment by SoMuchForSubtlety** [comment]
with `(?=(?:[^<code>]*<code>[^</code>]*</code>)*[^<code>]*$)`  I wanted to check that only closed `<code>`tags exist after the emote, but forgot that `[^<code>]` acts as a list and therefore also matches `c`, `o`, etc.

I can't think of an easy way to only have it match `<code>`

A possible solution would be to insert special characters before and after code 
`<code> ${betweenTicks} </code>`
and detect those with
`(?=(?:[^ ]* [^ ]* )*[^ ]*$)`

In this case I used a 1/6 width space

This would also address empty code disappearing mentioned in #96 .

**Comment by xDashh** [comment]
Closed by https://github.com/MemeLabs/chat-gui/commit/b8b44364f18846dcc6287aee70efb07e1c2e1bca
